### ISSUE TITLE
Docs don't work

### ISSUE THREAD

**Issue by bartonhammond** [leomorpho/goship#6]
Use the `get Started` button and Docs don't work `https://goship.run/docs/architecture` for example - just empty.
<img width="1294" alt="Screenshot 2024-10-25 at 10 16 13 AM" src="https://github.com/user-attachments/assets/c87dd052-9f6d-425a-a878-4930ae06c84b">

**Comment by leomorpho** [comment]
Indeed, sorry about that. I actually should just remove them for now to not confuse people. I had planned to extend them, but got side tracked and won't be working on them in the near future. Apart from the README, there are no other docs for now. 
Now, most of the documentation from Pagoda is still valid for goship, it's more for repos that there is no documentation, but hopefully they are clear enough in code.
